options:
  protocol:
    type: string
    default: 'layer2'
    description: |
      Type of configuration to use to announce service IPs. Upstream MetalLB supports
      both Layer 2 and BGP configuration. This charm currently only support the
      option 'layer2'. The layer 2 configuration works by responding to ARP requests
      on your local network directly, to give the machine's MAC address to clients.
  iprange:
    type: string
    default: "192.168.1.240-192.168.1.250"
    description: |
      For the Layer 2 Configuration only. This is the IP range from which MetalLB
      will have control over and choose IPs from to distribute to kubernetes services
      requesting an external IP of type Load Balancer. 
      Format of the range (no spaces): "192.168.1.240-192.168.1.250"
